name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature! Please provide detailed and clear information so we can fully understand your request.

  - type: input
    id: feature-title
    attributes:
      label: Add a Title
      description: Brief, descriptive title of your feature request.
      placeholder: ex. Improve search filtering functionality
    validations:
      required: true

  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. For example, "I'm always frustrated when..."
      placeholder: Describe the problem here...
    validations:
      required: true

  - type: textarea
    id: desired-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
      placeholder: List any other approaches or workarounds...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Include links, images, or additional notes...
    validations:
      required: false
